global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "link-analytics-fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "api_1:8000"
          - "api_2:8000"
          - "api_3:8000"
        labels:
          app: "link-analytics-platform"
